---
title: "Subclustering Microglia"
author: "James Choi"
date: "`r Sys.Date()`"
output:  
  html_document:
    keep_md: true
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.width=5.5, fig.height=4, fig.align='center', results='hold')

cc_genes_path <- '../ref/regev_lab_cell_cycle_genes.txt'
results_outpath <- '../results/20200708_GeneOntology/'
microglia_inpath <- '../results/20200625_subclustering_microglia/'
microglia_data <- '../data/20200625_microglia.rds'
nsc_inpath <- '../results/20200625_subclustering_nsc/'
nsc_data <- '../data/20200625_nsc.rds'

set.seed(123)
```

```{r library_data}
dir.create(path = results_outpath)
library('SingleCellExperiment')
library('Seurat')
library('dplyr')
library('ggplot2')
library('biomaRt')
library('topGO')
library('org.Mm.eg.db')

microglia <- readRDS(microglia_data)
nsc <- readRDS(nsc_data)
```


```{r name_conversions}
listEnsembl(version = 92)
ensembl <- useEnsembl(biomart = 'ENSEMBL_MART_ENSEMBL', dataset = 'mmusculus_gene_ensembl', version = 92)

conversion_input <- union(rownames(microglia[['RNA']]@counts), rownames(nsc[['RNA']]@counts))
conversion_input <- plyr::mapvalues(conversion_input, 'Sepp1', 'Selenop')
ensembl_conversion <- getBM(attributes = c('mgi_symbol','ensembl_gene_id','external_gene_name'),
                            filters = 'external_gene_name',
                            values = conversion_input,
                            mart = ensembl)

global_set <- rownames(microglia[['RNA']]@counts)
global_set <- plyr::mapvalues(x = global_set, from = 'Sepp1', to = 'Selenop')
global_set <- plyr::mapvalues(x = global_set,
                              from = ensembl_conversion$external_gene_name,
                              to = ensembl_conversion$ensembl_gene_id,
                              warn_missing = FALSE)
```


```{r microglia_GO, results='hide', fig.width=20, fig.height=14}
microglia_markers <- readRDS(file = paste0(microglia_inpath, 'microglia_de_markers.rds'))

microglia_markers$gene <- plyr::mapvalues(x = microglia_markers$gene,
                                from = c('Sepp1'), 
                                to = c('Selenop'))
microglia_markers$ensembl <- plyr::mapvalues(x = microglia_markers$gene, 
                                   from = ensembl_conversion$external_gene_name,
                                   to = ensembl_conversion$ensembl_gene_id,
                                   warn_missing = FALSE)
no_match <- unique(microglia_markers$gene[microglia_markers$gene %in% global_set[!grepl('ENS', global_set)]])
microglia_markers <- microglia_markers[!microglia_markers$gene %in% no_match,]

microglia_markers$cluster <- as.numeric(as.character(microglia_markers$cluster))
subtype <- levels(microglia$seurat_clusters)
microglia_GO <- vector(mode = 'list')

for(i in 1:length(subtype)) {
  # upregulated
  tmp <- microglia_markers[microglia_markers$avg_logFC > 0 & microglia_markers$cluster == (i-1),] %>% .[c('gene','p_val_adj','ensembl')]
  test_genes <- c(tmp$p_val_adj, rep(1, sum(!global_set %in% tmp$ensembl)))
  # test_genes <- c(tmp$p_val_adj)
  names(test_genes) <- c(tmp$ensembl, global_set[!global_set %in% tmp$ensembl])
  # names(test_genes) <- tmp$ensembl
  GOdata <- new("topGOdata", 
                ontology = "BP", 
                allGenes = test_genes, 
                geneSel = function(p) p < 1e-03, 
                description = "",
                annot = annFUN.org, 
                mapping="org.Mm.eg.db", 
                ID="Ensembl")
  GOres <- runTest(GOdata, algorithm = "classic", statistic = "fisher")
  upreg <- GenTable(GOdata, pvalue = GOres, topNodes = 50)
  upreg$cluster <- i-1
  microglia_GO[[i]] <- upreg
}

# Write results as csv
for(i in 1:length(subtype)) {
  tmp_name <- paste0(results_outpath, 'microglia_', 'cluster', i-1, '_GOterms.csv')
  write.csv(x = microglia_GO[[i]], 
            file = tmp_name,
            quote = FALSE,
            row.names = FALSE)
}

# Visualization
GO_plots <- vector(mode = 'list', length = length(subtype))
for(i in 1:length(subtype)) {
  tmp <- microglia_GO[[i]]
  tmp <- tmp[,c("GO.ID","Term","pvalue")]
  tmp$Term <- gsub(" [a-z]*\\.\\.\\.$", "", tmp$Term)
  tmp$Term <- gsub("\\.\\.\\.$", "", tmp$Term)
  tmp$Term <- paste(tmp$GO.ID, tmp$Term, sep=", ")
  tmp$Term <- factor(tmp$Term, levels=rev(tmp$Term))
  tmp$pvalue <- as.numeric(tmp$pvalue)
  GO_plots[[i]] <- tmp[1:20,] %>%
    ggplot(mapping = aes(x = Term, y = -log10(pvalue))) +
    geom_bar(position = 'dodge', stat = 'identity') +
    xlab("Biological process") +
    ylab("Enrichment") +
    labs(title = paste('Cluster', i-1, 'GO Enrichment')) +
    scale_y_continuous(breaks = round(seq(0, max(-log10(tmp$pvalue)), by = 2), 1)) +
    theme_bw(base_size = 18) +
    theme(legend.position = 'none',
          legend.background = element_rect(),
          plot.title = element_text(angle = 0, size = 24, face = "bold", vjust = 1),
          axis.text.x = element_text(angle = 0, size = 14, face = "bold", hjust = 1),
          axis.text.y = element_text(angle = 0, size = 14, face = "bold", vjust = 0.5),
          axis.title = element_text(size = 24, face = "bold"),
          legend.key = element_blank(),     #removes the border
          legend.key.size = unit(1, "cm"),      #Sets overall area/size of the legend
          legend.text = element_text(size = 18),  #Text size
          title = element_text(size = 18)) +
    guides(colour = guide_legend(override.aes = list(size = 2.5))) +
    coord_flip()
}
GO_plot_final <- cowplot::plot_grid(plotlist = GO_plots, ncol = 2)
GO_plot_final
ggsave(filename = paste0(results_outpath, 'microglia_GOterms_bargraph.tiff'),
       plot = GO_plot_final,
       device = 'tiff',
       height = 14,
       width = 20)
```


```{r nsc_GO, results='hide', fig.width=20, fig.height=14}
nsc_markers <- readRDS(file = paste0(nsc_inpath, 'nsc_de_markers.rds'))

nsc_markers$gene <- plyr::mapvalues(x = nsc_markers$gene,
                                from = c('Sepp1'), 
                                to = c('Selenop'))
nsc_markers$ensembl <- plyr::mapvalues(x = nsc_markers$gene, 
                                   from = ensembl_conversion$external_gene_name,
                                   to = ensembl_conversion$ensembl_gene_id,
                                   warn_missing = FALSE)
no_match <- unique(nsc_markers$gene[nsc_markers$gene %in% global_set[!grepl('ENS', global_set)]])
nsc_markers[nsc_markers$gene %in% no_match,] # Most p-val < 0.001
nsc_markers <- nsc_markers[!nsc_markers$gene %in% no_match,]

nsc_markers$cluster <- as.numeric(as.character(nsc_markers$cluster))
subtype <- levels(nsc$seurat_clusters)
nsc_GO <- vector(mode = 'list')

for(i in 1:length(subtype)) {
  # upregulated
  tmp <- nsc_markers[nsc_markers$avg_logFC > 0 & nsc_markers$cluster == (i-1),] %>% .[c('gene','p_val_adj','ensembl')]
  test_genes <- c(tmp$p_val_adj, rep(1, sum(!global_set %in% tmp$ensembl)))
  # test_genes <- c(tmp$p_val_adj)
  names(test_genes) <- c(tmp$ensembl, global_set[!global_set %in% tmp$ensembl])
  # names(test_genes) <- tmp$ensembl
  GOdata <- new("topGOdata", 
                ontology = "BP", 
                allGenes = test_genes, 
                geneSel = function(p) p < 1e-03, 
                description = "",
                annot = annFUN.org, 
                mapping="org.Mm.eg.db", 
                ID="Ensembl")
  GOres <- runTest(GOdata, algorithm = "classic", statistic = "fisher")
  upreg <- GenTable(GOdata, pvalue = GOres, topNodes = 50)
  upreg$cluster <- i-1
  nsc_GO[[i]] <- upreg
}

# Write results as csv
for(i in 1:length(subtype)) {
  tmp_name <- paste0(results_outpath, 'nsc_', 'cluster', i-1, '_GOterms.csv')
  write.csv(x = nsc_GO[[i]], 
            file = tmp_name,
            quote = FALSE,
            row.names = FALSE)
}

# Visualization
GO_plots <- vector(mode = 'list', length = length(subtype))
for(i in 1:length(subtype)) {
  tmp <- nsc_GO[[i]]
  tmp <- tmp[,c("GO.ID","Term","pvalue")]
  tmp$Term <- gsub(" [a-z]*\\.\\.\\.$", "", tmp$Term)
  tmp$Term <- gsub("\\.\\.\\.$", "", tmp$Term)
  tmp$Term <- paste(tmp$GO.ID, tmp$Term, sep=", ")
  tmp$Term <- factor(tmp$Term, levels=rev(tmp$Term))
  tmp$pvalue <- as.numeric(tmp$pvalue)
  GO_plots[[i]] <- tmp[1:20,] %>%
    ggplot(mapping = aes(x = Term, y = -log10(pvalue))) +
    geom_bar(position = 'dodge', stat = 'identity') +
    xlab("Biological process") +
    ylab("Enrichment") +
    labs(title = paste('Cluster', i-1, 'GO Enrichment')) +
    scale_y_continuous(breaks = round(seq(0, max(-log10(tmp$pvalue)), by = 2), 1)) +
    theme_bw(base_size = 18) +
    theme(legend.position = 'none',
          legend.background = element_rect(),
          plot.title = element_text(angle = 0, size = 24, face = "bold", vjust = 1),
          axis.text.x = element_text(angle = 0, size = 14, face = "bold", hjust = 1),
          axis.text.y = element_text(angle = 0, size = 14, face = "bold", vjust = 0.5),
          axis.title = element_text(size = 24, face = "bold"),
          legend.key = element_blank(),     #removes the border
          legend.key.size = unit(1, "cm"),      #Sets overall area/size of the legend
          legend.text = element_text(size = 18),  #Text size
          title = element_text(size = 18)) +
    guides(colour = guide_legend(override.aes = list(size = 2.5))) +
    coord_flip()
}
GO_plot_final <- cowplot::plot_grid(plotlist = GO_plots, ncol = 2)
GO_plot_final
ggsave(filename = paste0(results_outpath, 'nsc_GOterms_bargraph.tiff'),
       plot = GO_plot_final,
       device = 'tiff',
       height = 14,
       width = 20)
```


