---
title: "Ligand-Receptor Interaction Analysis"
author: "James Choi"
date: "`r Sys.Date()`"
output:  
  html_document:
    keep_md: true
    code_folding: show
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.width=5.5, fig.height=4, fig.align='center', results='hold')
```

```{r load_libraries}
library('Seurat')
library('ggplot2')
library('dplyr')
library('ggrepel')
source('LRfunctions.R')
source('VolcanoPlot.R')
```

```{r load_data}
svz <- readRDS(file = '../data/20200511_SVZ.rds')
lr_ref <- '../ref/fantom_PairsLigRec_mouse.csv'
lr_ref <- read.csv(file = lr_ref)
results_path <- '../results/20200806_LigandReceptorAnalysis/'
dir.create(path = results_path)
```

```{r calculate_LR_scores}
svz$full_clusters <- svz$RNA_snn_res.0.8
svz$celltype <- plyr::mapvalues(x = svz$RNA_snn_res.0.8,
                                from = 0:7,
                                to = c('Microglia',
                                       'Microglia',
                                       'Microglia',
                                       'NSC',
                                       'NSC',
                                       'NSC',
                                       'Microglia',
                                       'Unknown'))
Idents(svz) <- 'celltype'
DefaultAssay(svz)
my_setup <- setupLR(seurat_object = svz, lr_ref = lr_ref, split_by = 'orig.ident')
my_results <- calculateLR(setup = my_setup)
write.csv(x = my_results, file = paste0(results_path, 'LR_results_celltype.csv'), quote = FALSE)
```

```{r DE_tests, fig.height=10, fig.width=14}
# Changes in microglia gene expression after injury
microglia_1d_ctrl <- FindMarkers(object = svz,
                                 subset.ident = 'Microglia',
                                 group.by = 'orig.ident',
                                 ident.1 = 'S1d',
                                 ident.2 = 'SCtrl',
                                 logfc.threshold = 0)
microglia_7d_1d <- FindMarkers(object = svz,
                               subset.ident = 'Microglia',
                               group.by = 'orig.ident',
                               ident.1 = 'S7d',
                               ident.2 = 'S1d', 
                               logfc.threshold = 0)
microglia_7d_ctrl <- FindMarkers(object = svz,
                                 subset.ident = 'Microglia',
                                 group.by = 'orig.ident',
                                 ident.1 = 'S7d',
                                 ident.2 = 'SCtrl',
                                 logfc.threshold = 0)
# volcano plots
microglia_1d_ctrl_volcano <- VolcanoPlot(de_results = microglia_1d_ctrl,
                                         label_by_fc = 0.75,
                                         label_by_pval = 0.001,
                                         label_size = 5) +
  labs(title = 'S1d vs SCtrl',
       subtitle = 'Log2(fold-change) > 0 indicates higher expression in S1d') +
  theme(plot.title = element_text(size = 16, color = 'black'))
microglia_7d_1d_volcano <- VolcanoPlot(de_results = microglia_7d_1d,
                                       label_by_fc = 0.75,
                                       label_by_pval = 0.001,
                                       label_size = 5) +
  labs(title = 'S7d vs S1d',
       subtitle = 'Log2(fold-change) > 0 indicates higher expression in S7d') +
  theme(plot.title = element_text(size = 16, color = 'black'))
microglia_7d_ctrl_volcano <- VolcanoPlot(de_results = microglia_7d_ctrl,
                                         label_by_fc = 0.2,
                                         label_by_pval = 0.001,
                                         label_size = 5) +
  labs(title = 'S7d vs SCtrl',
       subtitle = 'Log2(fold-change) > 0 indicates higher expression in S7d') +
  theme(plot.title = element_text(size = 16, color = 'black'))
microglia_volcano <- cowplot::plot_grid(microglia_1d_ctrl_volcano,
                                        microglia_7d_1d_volcano, 
                                        microglia_7d_ctrl_volcano, 
                                        ncol = 3)

# Changes in NSC gene expression after injury
# Here I apply a multiple hypothesis correction via the "use_adj_pval" option of
# the VolcanoPlot() function. Previously on 2020/07/31, I set this option to 
# FALSE.
nsc_1d_ctrl <- FindMarkers(object = svz,
                           subset.ident = 'NSC',
                           group.by = 'orig.ident',
                           ident.1 = 'S1d',
                           ident.2 = 'SCtrl')
nsc_7d_1d <- FindMarkers(object = svz,
                         subset.ident = 'NSC',
                         group.by = 'orig.ident',
                         ident.1 = 'S7d',
                         ident.2 = 'S1d')
nsc_7d_ctrl <- FindMarkers(object = svz,
                           subset.ident = 'NSC',
                           group.by = 'orig.ident',
                           ident.1 = 'S7d',
                           ident.2 = 'SCtrl')
nsc_1d_ctrl_volcano <- VolcanoPlot(de_results = nsc_1d_ctrl,
                                   label_by_fc = 0.5,
                                   label_by_pval = 0.001,
                                   label_size = 5) +
  labs(title = 'S1d vs SCtrl',
       subtitle = 'Log2(fold-change) > 0 indicates higher expression in S1d') +
  theme(plot.title = element_text(size = 16, color = 'black'))
nsc_7d_1d_volcano <- VolcanoPlot(de_results = nsc_7d_1d,
                                 label_by_fc = 0.5,
                                 label_by_pval = 0.001,
                                 label_size = 5) +
  labs(title = 'S7d vs S1d',
       subtitle = 'Log2(fold-change) > 0 indicates higher expression in S7d') +
  theme(plot.title = element_text(size = 16, color = 'black'))
nsc_7d_ctrl_volcano <- VolcanoPlot(de_results = nsc_7d_ctrl,
                                         label_by_fc = 0.75,
                                         label_by_pval = 0.001,
                                         label_size = 5) +
  labs(title = 'S7d vs SCtrl',
       subtitle = 'Log2(fold-change) > 0 indicates higher expression in S7d') +
  theme(plot.title = element_text(size = 16, color = 'black'))
nsc_volcano <- cowplot::plot_grid(nsc_1d_ctrl_volcano, 
                                  nsc_7d_1d_volcano, 
                                  nsc_7d_ctrl_volcano,
                                  ncol = 3)
de_genes_over_time <- cowplot::plot_grid(microglia_volcano, nsc_volcano, ncol = 1)
ggsave(filename = paste0(results_path, 'DEgenes_byTime_volcanoplot.tiff'), 
       plot = de_genes_over_time,
       device = 'tiff',
       height = 10, width = 12)
de_genes_over_time
```


```{r identify_LR_using_DEgenes, fig.width=11.5, fig.height=4.5}
top_n <- 300
top_genes_1 <- rownames(microglia_1d_ctrl[order(abs(microglia_1d_ctrl$avg_logFC), decreasing = TRUE),])[1:top_n]
top_genes_2 <- rownames(microglia_7d_1d[order(abs(microglia_7d_1d$avg_logFC), decreasing = TRUE),])[1:top_n]
top_genes_3 <- rownames(microglia_7d_ctrl[order(abs(microglia_7d_ctrl$avg_logFC), decreasing = TRUE),])[1:top_n]
top_genes_microglia <- unique(c(top_genes_1, top_genes_2, top_genes_3))

top_genes_1 <- rownames(nsc_1d_ctrl[order(abs(nsc_1d_ctrl$avg_logFC), decreasing = TRUE),])[1:top_n]
top_genes_2 <- rownames(nsc_7d_1d[order(abs(nsc_7d_1d$avg_logFC), decreasing = TRUE),])[1:top_n]
top_genes_3 <- rownames(nsc_7d_ctrl[order(abs(nsc_7d_ctrl$avg_logFC), decreasing = TRUE),])[1:top_n]
top_genes_nsc <- unique(c(top_genes_1, top_genes_2, top_genes_3))

top_genes <- union(top_genes_microglia, top_genes_nsc)
tmp_lr_results <- my_results[my_results$Ligand %in% top_genes | my_results$Receptor %in% top_genes,]

LR_plots1 <- plotLR(results = tmp_lr_results,
                    l_cells = 'Microglia',
                    r_cells = 'NSC',
                    split_along_y = TRUE)
LR_plots1
ggsave(filename = paste0(results_path, 'LRplots_byDEgenes.tiff'),
       plot = LR_plots1,
       device = 'tiff',
       height = 4.5, width = 11.5)
```

```{r identify_LRs_by_score, fig.width=9, fig.height=4.5}
my_results_known <- my_results[my_results$Pair_name %in% lr_ref$Pair.Name[lr_ref$Pair.Source == 'known'],]
my_results_known <- my_results_known[my_results_known$pval < 0.05,]
my_results_known <- my_results_known[order(my_results_known$Score, decreasing = TRUE),]

LR_plots2 <- plotLR(results = my_results_known,
                    l_cells = 'Microglia',
                    r_cells = 'NSC',
                    split_along_y = TRUE)
LR_plots2
ggsave(filename = paste0(results_path, 'LRplots_allFantomKnown.tiff'),
       plot = LR_plots2,
       device = 'tiff',
       height = 4.5, width = 9)
```

```{r save_data}
save.image(file = paste0(results_path, 'sessionData.RData'))
```

```{r session_info}
sessionInfo()
```